apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: predictor
resources:
- namespace.yaml
- pvc.yaml
- secret.yaml
- service.yaml
- deployment.yaml
- hpa.yaml
- ../monitoring/servicemonitor.yaml
- ../training/cronjob-retrain.yaml # This will be a generic placeholder
- ../serving/ingress.yaml
