apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap-mlp.yaml

patchesStrategicMerge:
- deployment-patch.yaml

nameSuffix: -mlp

images:
- name: your-registry.io/predictor-serve
  newName: swift-ecommerce-predictor
  newTag: mlp-latest
