apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- configmap.yaml

patchesStrategicMerge:
- deployment-patch.yaml

nameSuffix: -tft

images:
- name: your-registry.io/predictor-serve
  newName: swift-ecommerce-predictor
  newTag: tft-latest
